# Deep Learning | Perceptron

Objectives:

1. Understand the structure and functionality of the perceptron
2. Implement a perceptron
3. Train a model for binary classification

In [1]:
import os.path
import torch
import torch.nn as nn

In [2]:
X = torch.tensor([[0.0, 0.0], [0.0, 1.0], [1.0, 0.0], [1.0, 1.0]])
Y = torch.tensor([[0.0], [0.0], [0.0], [1.0]])

let's say, input_size = 2 <br>
[x1, x2]<br>
[w1, w2]<br>
b<br><br>

parameters freezing: we may sometimes need to stop calculating gradients for certain parameters

In [3]:
class Perceptron(nn.Module):
    def __init__(self, input_size):
        super(Perceptron, self).__init__()
        
        self.input_size = input_size
        self.weight = nn.Parameter(torch.randn(input_size))
        self.bias = nn.Parameter(torch.zeros(1))
        
    def forward(self, x):
        z = x @ self.weight + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred

In [4]:
model = Perceptron(input_size=2)

""" Checkpoint """
if os.path.exists('my_model.pt'):
    model.load_state_dict(torch.load('my_model.pt'))
    print('Model loaded!')

In [5]:
torch.manual_seed(42)

x = torch.randn(2)
print(x)

y = model(x)
print(y)

tensor([0.3367, 0.1288])
tensor([0.5045], grad_fn=<SigmoidBackward0>)


In [6]:
print(*model.parameters())

Parameter containing:
tensor([-0.0702,  0.3219], requires_grad=True) Parameter containing:
tensor([0.], requires_grad=True)


In [7]:
criterion = nn.BCELoss()
optimizer = torch.optim.Adam(
    model.parameters(),
    lr=0.001
)

for epoch in epochs:
   1. prediction = model(x)
   2. calculate loss
   3. calculate gradient
   4. update weight

In [8]:
def train_model(model, epochs):
    for epoch in range(epochs):
        """ Prediction """
        y_pred = model(X)
        
        """ Loss calculation """
        loss = criterion(y_pred.unsqueeze(1), Y)

        """ Calculate gradient """
        optimizer.zero_grad()
        loss.backward()

        """ Update weight """
        optimizer.step()
        
        if epoch % 1000 == 0:
            print(f'Epoch: {epoch}, Loss: {loss.item():.4f}')

In [11]:
train_model(model, epochs=10000)

Epoch: 0, Loss: 0.0574
Epoch: 1000, Loss: 0.0452
Epoch: 2000, Loss: 0.0356
Epoch: 3000, Loss: 0.0280
Epoch: 4000, Loss: 0.0220
Epoch: 5000, Loss: 0.0173
Epoch: 6000, Loss: 0.0136
Epoch: 7000, Loss: 0.0107
Epoch: 8000, Loss: 0.0084
Epoch: 9000, Loss: 0.0066


In [12]:
def predict(model, X):
    model.eval()
    with torch.no_grad():
        test_output = model(X)
    return test_output

predict(model, X)

tensor([3.3657e-07, 6.9032e-03, 6.9080e-03, 9.9309e-01])

In [19]:
print(*model.parameters())

Parameter containing:
tensor([9.9363, 9.9356], requires_grad=True) Parameter containing:
tensor([-14.9045], requires_grad=True)


In [17]:
torch.save(model.state_dict(), '../Model/perceptron_model.pt')

## Load the model 
1. For prediction
2. For resuming training.

In [18]:
loaded_model = Perceptron(input_size=2)

loaded_model.load_state_dict(torch.load('../Model/perceptron_model.pt'))

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_19164\1116106025.py:3: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  loaded_model.load_state_dict(torch.load('../Model/perceptron

<All keys matched successfully>

In [20]:
print(*loaded_model.parameters())

Parameter containing:
tensor([9.9363, 9.9356], requires_grad=True) Parameter containing:
tensor([-14.9045], requires_grad=True)
