# Numpy - Axis and Random
Objectives:

1. We will understand numpy axis
   - concatenate
   - sum
2. We will learn how to use random

In [2]:
import numpy as np

# matrix transpose 

In [3]:

my_2d_array_1 = np.array(
    [[2, 1, 3],
     [7, 5, 6]]
)

print(my_2d_array_1.T)
#print(my_2d_array_1.transpose())

[[2 7]
 [1 5]
 [3 6]]


 # Reshaping with -1

In [4]:

my_2d_array_1 = np.array(
    [[2, 1, 3],
     [7, 5, 6]]
)

print(my_2d_array_1.reshape(-1))

[2 1 3 7 5 6]


# Reshape the input array into (3, 80)

In [6]:
my_np_array = np.empty((3, 4, 2, 10))

print(my_np_array.shape)

print(my_np_array.reshape(3, -1).shape)
print(my_np_array)

(3, 4, 2, 10)
(3, 80)
[[[[1.19619589e-311 1.19616850e-311 5.33096832e-321             nan
    4.94065646e-322 3.95984655e+257 9.03292329e+271 1.52535471e+190
    3.18487602e-114 8.56486049e+183]
   [1.15992674e+253 4.82191872e+233 6.22651684e+228 2.21525978e+214
    8.56486049e+183 4.77402336e+180 1.10871574e+219 1.29778873e+243
    6.01346953e-154 2.59441390e+161]]

  [[2.45474676e+198 4.19338640e+228 1.47311266e+171 7.13222113e-154
    4.96042866e+180 1.88777559e+219 6.23537913e+228 5.72093048e+188
    2.02763010e+174 2.46291819e+198]
   [1.69264133e-139 6.62901802e+265 6.20280733e+223 4.70102441e+180
    6.23537913e+228 1.49005471e+195 4.44003833e+252 2.86530675e+161
    7.13222113e-154 3.98837334e+252]]

  [[2.16194291e+233 7.10233174e+194 1.33293953e+179 5.29061148e+180
    8.92883155e+271 1.81596891e-152 5.28964318e+180 1.69264133e-139
    3.98837335e+252 1.06400624e+248]
   [4.72883470e+164 8.73977450e+183 1.00953367e+190 3.27842380e-085
    9.82157873e+252 4.81418925e+199 1.391

In [7]:
print(np.ones((3, 4, 2, 2)).reshape(2, -1, 2).shape)

(2, 12, 2)


In [8]:
""" Get columns from a numpy array """

my_np_array = np.empty((4, 2))

print(my_np_array)
print(my_np_array[0,:])

print(my_np_array[:,[0]])

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[0. 0.]
[[0.]
 [0.]
 [0.]
 [0.]]


In [9]:
my_np_array = np.empty((3, 4, 2))

print(my_np_array[:,[0, 2],:].shape)

(3, 2, 2)


# Numpy Axis: concatenate()

In [10]:
my_2d_array_1 = np.array(
    [[1, 1, 1],
     [1, 1, 1]]
)

my_2d_array_2 = np.array(
    [[2, 2, 2], 
     [2, 2, 2]]
)

my_2d_array_joined = np.concatenate(
    (my_2d_array_1, my_2d_array_2), 
    axis=1
)

print(my_2d_array_joined)
print("my_2d_array_1.shape", my_2d_array_1.shape)
print("my_2d_array_2.shape", my_2d_array_2.shape)
print("my_2d_array_joined.shape", my_2d_array_joined.shape)

[[1 1 1 2 2 2]
 [1 1 1 2 2 2]]
my_2d_array_1.shape (2, 3)
my_2d_array_2.shape (2, 3)
my_2d_array_joined.shape (2, 6)


In [11]:
# (4, 2, 10) = (axis=0, axis=1, axis=2)
my_md_array_1 = np.empty((4, 2, 10))
my_md_array_2 = np.empty((4, 2, 10))

my_md_array_joined = np.concatenate(
    (my_md_array_1, my_md_array_2),
    axis=0,
)

my_md_array_joined.shape

(8, 2, 10)

# Sum => aggregation

In [12]:

my_np_array = np.array(
    [[1, 5, -2],
     [0, 1, 9]]
)

print(my_np_array.shape)
print(np.sum(my_np_array, axis=0))
print(np.sum(my_np_array, axis=0).shape)

(2, 3)
[1 6 7]
(3,)


In [15]:
my_np_array = np.empty((2, 4, 12, 10))
# print(my_np_array)
print(np.sum(my_np_array, axis=2).shape)
# print(my_np_array)

(2, 4, 10)


# Random
- rand()
- randint()

In [16]:

print(np.random.rand())
print(np.random.rand(4,2))
print(np.random.randint(100))
print(np.random.randint(100, size=(5,3)))

0.7566896694584352
[[0.91414693 0.51360789]
 [0.48322079 0.66800912]
 [0.56679242 0.59113659]
 [0.29648907 0.37301048]]
34
[[78 17 87]
 [45 10 18]
 [83 41 54]
 [25 48 60]
 [20 79 69]]


In [17]:
"""Random shuffle"""

np.random.seed(42)

my_array = np.random.randint(5, size=(5,))
print(my_array)
np.random.shuffle(my_array)
print(my_array)

[3 4 2 4 4]
[4 3 4 2 4]


# Use case: Split Dataset into Train, Test and Validation 

In [18]:

dataset = np.random.rand(1000, 5)
print("Dataset:\n", dataset[:5])

Dataset:
 [[4.59248892e-01 3.33708611e-01 1.42866818e-01 6.50888473e-01
  5.64115790e-02]
 [7.21998772e-01 9.38552709e-01 7.78765841e-04 9.92211559e-01
  6.17481510e-01]
 [6.11653160e-01 7.06630522e-03 2.30624250e-02 5.24774660e-01
  3.99860972e-01]
 [4.66656632e-02 9.73755519e-01 2.32771340e-01 9.06064345e-02
  6.18386009e-01]
 [3.82461991e-01 9.83230886e-01 4.66762893e-01 8.59940407e-01
  6.80307539e-01]]


In [19]:
np.random.shuffle(dataset)

In [20]:
dataset[:5]

array([[0.27561234, 0.7871266 , 0.97483465, 0.37120709, 0.42888688],
       [0.01363402, 0.32272657, 0.55435668, 0.14821746, 0.09209875],
       [0.87426247, 0.51010971, 0.72340477, 0.10413736, 0.22543876],
       [0.32350039, 0.83430337, 0.62929881, 0.19885628, 0.06461668],
       [0.55835232, 0.86993783, 0.37154651, 0.61440001, 0.52366342]])

In [21]:
""" Step 2. Split """

index_1 = int(0.8 * len(dataset))
index_2 = int(0.9 * len(dataset))

trainset, valset, testset = np.split(
    dataset,
    [index_1, index_2],
)
print(len(trainset), len(valset), len(testset))

800 100 100



Dera => No idea what inside => unknown data generator

Dakat's information => 
list of information (height, weight, color, weapon) => sample dataset / sample output from the unknown data generator (dataset)

=> trying to predict/mimic unknown data generator (ml) using ml algorithms

=> To test our ml algorithm we use testset, and use trainset for learning the ml algorithm and valset to evaluate our ml algorithm when it is trained on trainset
