In [7]:
""" Numpy - The Basics
- Numpy stands for numerical python
- NumPy is a Python library.
- NumPy is used for working with arrays. 
- 50x faster than list
- supports vectorization

Prerequisites:
==============
- How to use Jupyter Notebook
- Basic python
 
Objectives:
===========
1. We will learn how to create a numpy array
2. We will understand numpy indexing
3. We will slice numpy array
4. We will filter elements from a numpy array
5. We will also know the difference between copy and view
6. We will reshape, sort, iterate over a numpy array
"""

"""A cell"""
import numpy as np

np.__version__

'1.26.4'

In [8]:
"""numpy array creation
- dtype
- shape
- ndim
"""

my_np_array = np.array([1, 2, 3])

print(my_np_array)
print(my_np_array.dtype)
print(my_np_array.shape)
print(my_np_array.ndim)

[1 2 3]
int32
(3,)
1


In [9]:
""" Create an array with all zeros
"""
zeros_np_array = np.zeros(shape=(5,), dtype='int')

zeros_np_array

array([0, 0, 0, 0, 0])

In [10]:
ones_np_array = np.ones(shape=(10,2), dtype='int')

print(ones_np_array)
print(ones_np_array.dtype)

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]
int32


In [11]:
assigned_with_specific_np_array = np.full(shape=(10,), fill_value=15,)

assigned_with_specific_np_array

array([15, 15, 15, 15, 15, 15, 15, 15, 15, 15])

In [22]:
identity_matrix = np.eye(4)
print(identity_matrix)
identity_matrix

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
my_empty_np_array = np.empty(shape=(5,))
my_empty_np_array

array([2.12199579e-314, 9.69752076e-312, 6.38332814e-321, 3.79442416e-321,
       9.69875004e-312])

In [24]:
"""Type cast"""

my_empty_np_array_int = my_empty_np_array.astype('int')
print(my_empty_np_array_int)

[0 0 0 0 0]


In [26]:
"""numpy array dimensions.
Mathematical objects
- scalar -> 0D
- vector -> 1D
- matrix -> 2D
- tensor -> xD
"""
my_0d_array = np.array(42)
print('0-dimensional array:', my_0d_array, 'ndim:', my_0d_array.ndim)

my_1d_array = np.array([1.5, 2, 3.3, 4.7, 5.1, 6]) 
print('1-dimensional array:', my_1d_array, 'ndim:', my_1d_array.ndim)

my_2d_array = np.array(
    [[1, 2, 3, 4],
     [5, 8, 9, 5],
     [7, 1, 2, 7]]
) 
print('2-dimensional array', 'ndim:', my_2d_array.ndim)
print(my_2d_array)

0-dimensional array: 42 ndim: 0
1-dimensional array: [1.5 2.  3.3 4.7 5.1 6. ] ndim: 1
2-dimensional array ndim: 2
[[1 2 3 4]
 [5 8 9 5]
 [7 1 2 7]]


In [16]:
"""numpy indexing
- non-negative indexing
- negative indexing
"""

my_np_array = np.array(
    [1, 2, 3, 4, 5]
)

print(my_np_array[2])
print(my_np_array[-3])

3
3


In [17]:
my_2d_array = np.array(
    [[1, 2, 3, 4],
     [5, 8, 9, 5],
     [7, 1, 2, 7]]
) 

print(my_2d_array[1,1])
print(my_2d_array[1,-3])

8
8


In [28]:
"""numpy slicing
- array_name[start:end] => open interval [start, end)
- array_name[start:end:step]
- end index is excluded
- default values: start=0, end=n, step=1
"""
print(my_1d_array.astype('int'))
print(my_1d_array[2:5])
print(my_1d_array[1:5:2])
# print(my_2d_array[0:2,1:3])

[1 2 3 4 5 6]
[3.3 4.7 5.1]
[2.  4.7]


In [19]:
print(my_2d_array)

[[1 2 3 4]
 [5 8 9 5]
 [7 1 2 7]]


In [20]:
print(my_2d_array[1:3,])

[[5 8 9 5]
 [7 1 2 7]]


In [21]:
"""numpy filter
- using boolean mask
- using conditionals
- using indices
- using custom filter method
"""

'numpy filter\n- using boolean mask\n- using conditionals\n- using indices\n- using custom filter method\n'