# Today's Topic
- numpy filter
- using boolean mask
- using conditionals
- using indices
- using custom filter method

# Objectives: 
1. We will learn important numpy functions
   - unique =>  unique values
   - argmax, argmin => finds the index of an max/min element in a numpy array
   - arange => creates sequential numpy arrays
   - linspace => creates sequential numpy arrays with linear space
   - split => splits a numpy array into different arrays
   - dot => creates sequential numpy arrays with dot product
   - mean, median, std => generate statistical values
   - concatenate (Check Axis in the PPT)
   - vstack, hstack
   - sum
2. We will learn how to use random
3. We will understand vectorization
4. We will understand Broadcasting

In [1]:

import numpy as np

In [2]:
np_array = np.array([1, 2, 3, 4, 5])
print(np_array)

[1 2 3 4 5]


# Boolean mask

In [3]:

filter_mask = [True, False, True, False, True]
new_array = np_array[filter_mask]
print(new_array)

[1 3 5]


# conditionals

In [4]:

filter_mask = np_array % 2 == 1 
new_array = np_array[filter_mask]
print(new_array)

[1 3 5]


# indices

In [5]:

indices = np.where(np_array % 2 == 1)
new_array = np_array[indices]
new_array

array([1, 3, 5])

# custom filter method

In [9]:

def my_filter_method(x):
    """Logic"""
    if x % 2 == 0:
        return False
    return True

filtered_iterable = filter(my_filter_method, np_array)
print(filtered_iterable)
my_filtered_array = np.array(
    list(filtered_iterable)
)

print(my_filtered_array)

[1 3 5]


# Copy and View
pass by value and pass by reference

In [11]:
print("Original array:", np_array)

my_np_array_copy = np_array.copy()

my_np_array_copy[0] = 7
print(my_np_array_copy)
print(np_array)

Original array: [1 2 3 4 5]
[7 2 3 4 5]
[1 2 3 4 5]


In [12]:
print("Original array:", np_array)

my_np_array_view = np_array.view()

my_np_array_view[0] = 7
np_array[4] = 10
print(my_np_array_view)
print(np_array)

Original array: [1 2 3 4 5]
[ 7  2  3  4 10]
[ 7  2  3  4 10]


# Numpy reshape
- Condition: multiplication of values before and after reshaping must be same


In [14]:
np_array = np.full(
    shape=(5, 3),
    dtype='int',
    fill_value=5,
)

my_np_array_reshaped = np_array.reshape(3, 5)

print(np_array.shape)
print(np_array)
print(my_np_array_reshaped.shape)
print(my_np_array_reshaped)

(5, 3)
[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]
(3, 5)
[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


# Numpy reshape
- Step 1. flattening -> 1D
- Step 2. reshaping


In [16]:
my_2d_array =  np.array([[1, 2, 3, 4], [5, 8, 9, 5], [7, 1, 2, 7]])
print(my_2d_array)
print(my_2d_array.flatten())
print(my_2d_array.reshape(2, 6))

[[1 2 3 4]
 [5 8 9 5]
 [7 1 2 7]]
[1 2 3 4 5 8 9 5 7 1 2 7]
[[1 2 3 4 5 8]
 [9 5 7 1 2 7]]


# Sort

In [17]:

prediction = [0.3, 0.3, 0.4]
print(np.sort(prediction))
print(np.sort(prediction)[::-1])

[0.3 0.3 0.4]
[0.4 0.3 0.3]


# Iteration

In [18]:
my_1d_array =  np.array([1, 2, 3, 4, 5])

print(my_1d_array)

"""Iterate by value"""
for x in my_1d_array:
    print(x, end=', ')
    
print()

"""Iterate by index"""
for i in range(len(my_1d_array)):
    print(my_1d_array[i], end=', ')
print()

"""Enumerate"""
for i, x in enumerate(my_1d_array):
    print(i, x)

[1 2 3 4 5]
1, 2, 3, 4, 5, 
1, 2, 3, 4, 5, 
0 1
1 2
2 3
3 4
4 5


# Unique Function

In [19]:
my_np_array = np.array([1, 5, 1, 1, 5, 7])
unique_elements = np.unique(my_np_array)
print(unique_elements)

[1 5 7]


# argmax/argmin function

In [20]:
index_max = np.argmax(my_np_array)
index_min = np.argmin(my_np_array)

print(index_max, index_min)

5 0


# arrange() function

In [21]:
my_array = np.arange(1, 10)
print(my_array)

[1 2 3 4 5 6 7 8 9]


# linspace() function

In [22]:
my_np_array = np.linspace(
    start=0,
    stop=10,
    num=5
)
print(my_np_array)

[ 0.   2.5  5.   7.5 10. ]


# split() function

In [23]:
my_np_array = np.array([1, 5, 1, 1, 5, 7])

new_np_array = np.split(
    my_np_array, 
    indices_or_sections=2
)
print(new_np_array)

[array([1, 5, 1]), array([1, 5, 7])]


# dot() function

In [24]:
#  *  = 1 x 3 + 2 x 4 + 3 x 5 = 26
my_np_array_1 = np.array(
    [1, 2, 3]
)

my_np_array_2 = np.array(
    [3, 4, 5]
)

print(my_np_array_1)
print(my_np_array_2)

dot_product = np.dot(my_np_array_1, my_np_array_2)
print(dot_product)

[1 2 3]
[3 4 5]
26


# mean(), median(), std()  function

In [25]:
print(np.mean(my_np_array_1))
print(np.median(my_np_array_1))
print(np.std(my_np_array_1))

2.0
2.0
0.816496580927726


# Vectorization

In [26]:

my_1d_array = np.array(
    [1, 2, 3, 4, 5]
)

print(my_1d_array)

my_1d_array % 2 == 1

[1 2 3 4 5]


array([ True, False,  True, False,  True])

In [32]:
my_1d_array = np.array(
    [1, 2, 3, 4, 5]
)

for x in my_1d_array:
    x = x + 5
    
my_1d_array = my_1d_array + 5
print(my_1d_array)

[ 6  7  8  9 10]


# Broadcasting
- converting a lower shape into higher shape for vectorization

In [37]:

# (2,)
# (4, 2)
w = np.array(
    [1, 2]
    )


x = np.array([
    [3, 4], 
    [5, 6],
    [7, -8],
    [-5, -3]
])

w * x

array([[  3,   8],
       [  5,  12],
       [  7, -16],
       [ -5,  -6]])

In [34]:
np.array([1, 2]) * np.array([3, 4])

array([3, 8])